[bibliography]
== BIBLIOGRAFIA CONSULTADA

[bibliography]
- AZEVEDO, R. A. B.; COELHO, F. M. G.; NOLASCO, F. *Agricultura
sustentável: inquietações, proposições e métodos*. In: Debate:
sustentabilidade e agricultura. Anais... 1997.

- ALLEN, R. *How to save the world*. London: Kogan Page, 1980.

- ARIZA, Dervile. *Ecologia objetiva*. São Paulo: Nobel, 1977.

- BARBIER, E. *The concept of sustentainable economic development*.
Environmental Conservation, v. 14, n. 2, p. 101-110, 1987.

- BRANCO, S. M. *A água e o homem*. Hidrografia ambiental. São Paulo:
EDUSP, 414p.

- BUDOWSKI, G. *La conservación de la naturaleza como instrumento
de desarrollo*. México, Instituto Mexicano de Recursos Naturales
Renovables, 1972. 31p.

- BUTELL, F. *Ideologia e tecnologia agrícolas no final do século:
biotecnologia como símbolo e substancia*. In: CONFERÊNCIA SOBRE
BIOTECNOLOGIA E AGRICULTURA. Roma, 1992. (Mimeo).

- CAMPOS, L. M. S. *Sistema de gestão e avaliação de desempenho
ambiental: uma proposta de implementação*. Tese (Doutorado)
Engenharia da Produção – UFSC, Florianópolis, 2001.

- COLEÇÃO ECOSSISTEMAS. *Floresta Tropical/ A vida no deserto/ A
vida nas Lagoas/ O mundo doa corais. São Paulo: Abril Jovem, 1991.
COLEÇÃO ATLAS VISUAIS. (Plantas / animais/ o corpo humano/ o
universo). São Paulo: Ática, 1995.

- DAJOZ, R. *Ecologia geral*. 3. ed. São Paulo/ Petrópolis: Vozes, 1983,
471p.

- DIAS, G. F. *Educação ambiental: princípios e prática*. 2. ed. São Paulo:
Gaia, 1993.

- GLEISMAN, N. R. *Agroecologia : processos ecológicos em
agricultura sustentável*. 2. ed. Porto Alegre: EDUFRS, 2001.

- GUSMAN, E. S. *Origem, evolução e perspectivas do desenvolvimento
sustentável*. In: ALMEIDA, J. NAVARRO, Z. Reconstruindo a
agricultura: idéias e ideais na perspectivas do desenvolvimento rural
sustentável. 2. ed. Porto Alegre: UFRGS, 1998.

- MEC – Ministério de Educação e do Desporto. *Educação Ambiental*.
Brasília, DF, 1997.

- `_____`. *Parâmetros Curriculares Nacionais*. Ciências Naturais. Brasília,
DF. 1998.
