[[prefacio]]
[preface]
== Prefácio

O texto sobre a disciplina 'Ecologia e Meio Ambiente', do Curso de Graduação em
Ciências – Licenciatura à Distância da UFPB procura apresentar, de uma maneira simples,
uma abordagem sucinta sobre o desenvolvimento científico e tecnológico alcançado pelo
homem até os dias atuais, colocando em suas mãos elementos capazes de destruir em
poucos segundos a maior parte dos seres viventes que povoam a terra.

A 'Ecologia e Meio Ambiente' como disciplina está situada no campo do conhecimento
das Ciências Naturais. É de se ressaltar sua importância pela aplicabilidade que tem dentro do
âmbito acadêmico, pois seus estudos são relevantes por seu caráter integrador nas Ciências
Naturais e, por outro lado, há uma necessária interdisciplinaridade de outras áreas do
conhecimento para que esta possa ser estudada.

Os conhecimentos de 'Ecologia e Meio Ambiente' englobam problemáticas ambientais
relacionadas com os fatores sociais, econômicos, ecológicos, políticos, culturais etc.,
enfatizando, por exemplo, o conhecimento dos importantes compostos orgânicos que
constituem os seres vivos, os quais fornecem energia para que estes seres realizem suas
funções biológicas, como também, a diversidade de organismos nos diferentes ambientes
com base na evolução que tiveram.

Na formação dos profissionais em Ciências Agrárias e outras profissões afins é de
fundamental importância conhecer amplamente o estudo da Ecologia, para poder entender e
atender as problemáticas ambientais que atormentam a todos e, assim, apresentar soluções.
Na situação atual, se faz necessário estudantes participativos, capazes de propor soluções
aplicáveis e funcionais à realidade em que o homem está inserido, assim como, realizar
diagnósticos dos impactos ambientais gerados pelas atividades humanas, configurando um
pensar abrangente e transversal, objetivando realizar estudos voltados para o diagnóstico,
prevenção, correção e/ou mitigação de problemas ambientais em ecossistemas, bem como
viabilizar o desenvolvimento sustentável.
